### ISSUE TITLE
有没有后端访问的例子

### ISSUE THREAD

**Issue by hefju** [ziyoung/ant-design-snippets#1]
我是新手，期待后端api访问的代码，怎样全局带token访问后端？

**Comment by ziyoung** [comment]
添加了 aioxs 的例子。[axios 的使用](https://github.com/ziyoung/ant-design-snippets/tree/master/doc/4%20%E6%B7%BB%E5%8A%A0%20axios) 以及  [axios.js](https://github.com/ziyoung/ant-design-snippets/blob/master/src/common/axios.js)。
