### ISSUE TITLE
你好，没找到邮箱，所以只能提个issue

### ISSUE THREAD

**Issue by masongzhi** [ziyoung/ant-design-snippets#2]
https://github.com/ElemeFE/element/issues/15046
![image](https://user-images.githubusercontent.com/19945145/57385817-b767e680-71e5-11e9-9108-4d8b692eadbb.png)
我对维护开源有兴趣，可以加入吗

**Comment by ziyoung** [comment]
@masongzhi 好的，你邮箱是？

**Comment by ziyoung** [comment]
@masongzhi 我邮箱 ZGVuZ3poaXlhbmcxMjNAMTI2LmNvbQ==

**Comment by masongzhi** [comment]
@ziyoung 你好，已经发你邮件了，我邮箱 IDUxMTA3MTE2MUBxcS5jb20=
